### ISSUE TITLE
[Compatibility Issue With Create Mod] Attempting to automate process using Create's Deployer results in crash

### ISSUE THREAD

**Issue by JuicyCosmos** [Mrbysco/Pathing-the-way#1]
## Client Info
* Minecraft Version: 1.16.5

* Forge Version: 36.1.0
* Mod Version: 1.0.2
* Java Version: Java 8

## This mod is very useful converting block and it even works with fluids! I'm also playing with Mr.Crayfish Vehicle mod but I find the fuel production much of a hassle. So in the configs I tried to add a shovel enderpearl block from Charm to ender sap fluid and Blaze Lantern from quark to blaze juice. These all work amazingly if I shovel the blocks myself, but if I give a shovel to Create's deployer  and attempt to let it do the work, the world crashed. Even if I removed the recipes in the configs, trying to rejoin the world would still insta-crash because of the ticking block entity and the problem is only solved when I removed this mod. 
P.s. If the mod is removed Create's deployers will not have problems using shovels to convert dirt into path, etc...

## Reproduce Steps
1. Add some recipes in configs
2. Set up an automation placing and converting the block, pumping the fluid afterwards
3. Give the Deployer the tool to convert the block
4. Give the contraption rotational

 power and BOOM
5. Crash

 For some reason I can't access pastebin.com so I'll just post the crashlog here
[Crash.txt](https://github.com/Mrbysco/Pathing-the-way/files/6216712/Crash.txt)

**Comment by Mrbysco** [comment]
Could you try 1.0.3?
https://www.curseforge.com/minecraft/mc-mods/pathing-the-way/files/3253725

**Comment by JuicyCosmos** [comment]
> Could you try 1.0.3?
> https://www.curseforge.com/minecraft/mc-mods/pathing-the-way/files/3253725

Wow that's a quick fix! The issue is fixed. I'm closing it now.
