### ISSUE TITLE
[Bug]: Overlapping behavior with Vanilla

### ISSUE THREAD

**Issue by Zwikkry** [Mrbysco/Pathing-the-way#2]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.0.52

### Mod version

1.0.3

### Java version

OpenJDK 17.0.1

### Issue Description

Adding the path conversion for "minecraft:dirt_path,minecraft:dirt" or anything dirt related that uses the shovel will overlap with vanilla behavior. This means that if you want to convert a dirt_path to dirt, the shovel will immediately turn it back into a dirth_path because this is vanilla behavior.

### Additional Information

https://user-images.githubusercontent.com/32293196/163593625-f5a53eb9-68a2-41d8-b124-86717f74e8d7.mp4

**Comment by Mrbysco** [comment]
A new jar has been uploaded to curseforge and will be available shortly
